[package]
name = "dars"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
dars-macros = { path = "../dars-macros" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
schemars = { version = "1.1.0" }
